server:
  port: 8083

spring:
  application:
    name: vip-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} # Ensures consistency in instance naming
    prefer-ip-address: true  # Uses IP instead of hostname
    hostname: localhost      # Explicitly set the hostname if needed (localhost in this case)
management:
  endpoints:
    jmx:
      exposure:
        include: health, info

